### ISSUE TITLE
new first level floor

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#102]
* 1000 sq/ft
* cork flooring
* cork underlayment

## Do First
- [x] wiring for new kitchen #103
- [x] raise ceiling for new kitchen #104 

## TODO
- [x] purchase/order cork flooring
- [x] store cork at 48-72 hours unboxed on-site
- [x] tear up teak flooring
    - [x] cover particle board subfloor with 1/4 plywood
- [x] level the entire floor (sand down / build up)
    - [x] purchase glue
    - [x] in front area, sand finish off oak flooring (use oak as subfloor)
    - [x] glue down the flooring

**Comment by msimerson** [comment]
Sand the finish off the floor.
![img_0075](https://user-images.githubusercontent.com/261635/33451061-90b4f2d2-d5c2-11e7-8a41-d196795c6bab.jpg)

Cover with 1/4 plywood (for bonding surface)
![img_0078](https://user-images.githubusercontent.com/261635/33451062-90ca20da-d5c2-11e7-8ba0-76806b5fb214.jpg)

Glued down and fastened with lots of screws:
![img_0080](https://user-images.githubusercontent.com/261635/33451064-90f08658-d5c2-11e7-8fbd-5a4c7f94a329.jpg)

Contact cement on the cork tiles & floor:
![img_0087](https://user-images.githubusercontent.com/261635/33451060-909ded6c-d5c2-11e7-9dc7-6c3603cecedd.jpg)

Fresh coats of polyurethane:
![img_0086](https://user-images.githubusercontent.com/261635/33451063-90de3a3e-d5c2-11e7-858d-bd7f810765d7.jpg)

**Comment by msimerson** [comment]
Update: the entire floor is laid, it's just waiting for nice outside weather to polyurethane coat it. We'll need the house to air out for hours afterwards..

**Comment by msimerson** [comment]
In early August '18 the living room floor was double coated with polyurethane and another coat was added to the traffic areas inside the kitchen.
