### ISSUE TITLE
Roof needs solar panels

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#13]
### reasons to do soon
1. WA state sustainable production incentives expire in 2020
2. 30% federal [tax credit](https://www.energystar.gov/about/federal_tax_credits) starts shrinking in 2019
3. WA state sales tax exemption
### todo
- [x] get quotes from installers
  - Sunergy: 9.90 kW for $30,424
  - NW Wind & Solar: 9.86 kW for $33,341
  - Puget Sound Solar: 8.1 kW for $32,762
- [x] choose installer
  - [x] schedule installation
- [x] panel installation
  - [x] permitting, ~7 days
  - [x] Fill out SCL interconnection agreement
  - [x] interconnection approval, ~7 days
  - [x] install panels on roof (starting May 19th).
  - [x] electrical inspection (May 24)
  - [x] install new production and digital net meters, ~7-10 days (expected May 31, actual June 8)
    - [x] get "made in WA" confirmation, 30 days (June 6)
- [x] receive 30% Federal tax credit (#70)
### options
- [x] put panels on East/West facing garage roof
  - roof is nearly new
- put panels on South facing house roof
  - depends on #18 (replace roofing)
### See also
- [Roofing](https://github.com/msimerson/330-NE-193rd-St/blob/master/ROOFING.md)
- [building code requirements](http://mybuildingpermit.com/Constuction%20Tip%20Sheets/2012%20Tip%20Sheets/MBP%20Tip%20Sheet%2024_2012a.pdf) at [mybuildingpermit.com](http://mybuildingpermit.com/Pages/construction-tip-sheets.aspx)
- related to #15 (electrical system)

**Comment by msimerson** [comment]
Annual Solar Production for 98155 (modeled with [PVWatts](http://pvwatts.nrel.gov))

| Azimuth | Tilt | Annual kWh |
| --- | --- | --- |
| 180 | 20 | 10675 |
| 180 | 35 | 10917 |
| 180 | 40 | 10875 |
| 270 | 5 | 9536 |
| 270 | 10 | 9539 |
| 270 | 20 | 9433 |
| 270 | 30 | 9199 |

**Comment by msimerson** [comment]
### Payback Tracking


| Year | Expenses | Rebates | Incentive(1) | Net Metering | Net Cost |
| --- | --: | --: | --: | --: | --: |
| 2016 | $33,341 | $10,002 | (#69) $688 | $664 | $21,888 |
| 2017 |  |  | $3,633 | $1,088 | $17,004 |
| 2018 |  |  | $3,778 | $1,360 | $11,661 |
| 2019 |  |  | $3,815 | $1,439 | $6,192 |
| 2020 |  |  | $3,500 | $1,517 | $948 |
| 2021 |  |  |  | $1,517 | $-859 |
| 2022 |  |  |  | $1,621 | -$2,736 |
| ..... |  |  |  | ....... | .......... |
| 2030 | $1,500 | | | $2,066 | -$14,187 | 
| ..... |  |  |  | ....... | .......... |
| 2046 |  |  |  | $3,869 | -$68,104 |
| Totals | $34,841 |  | **$15,414** | **$67,416** |  |

1. The 2030 expense is an expected inverter replacement.
2. WA state [renewable energy production incentive](http://programs.dsireusa.org/system/program/detail/378).
3. WSU [Renewable Energy System Incentive Program](http://www.energy.wsu.edu/RenewableEnergySystemIncentiveProgram.aspx)
4. Senate Bill [5939](http://lawfilesext.leg.wa.gov/biennium/2017-18/Pdf/Bills/Senate%20Passed%20Legislature/5939-S.PL.pdf#page=1)

### Notes
- Estimated annual electric rate increases are conservatively estimated at 4%. The [2017 and 2018 increases are 5.6%](https://www.seattle.gov/light/rates/)
- ~~the production incentive is expected to diminish over time, ending in 2020.~~
- the net metering value increases in value as retail electric rates increase.
- future $ amounts should be inflation adjusted but are not. Yet.

**Comment by msimerson** [comment]
View from the South:

![330_south](https://cloud.githubusercontent.com/assets/261635/15229020/c647f630-1843-11e6-8d34-6ab782d1749d.jpg)

**Comment by msimerson** [comment]
### install completed

![img_1168](https://cloud.githubusercontent.com/assets/261635/15598312/96181bf2-238d-11e6-915d-acf47be5b802.jpg)
![img_1169](https://cloud.githubusercontent.com/assets/261635/15598314/96323f82-238d-11e6-90c0-ef0522592777.jpg)
![img_1170](https://cloud.githubusercontent.com/assets/261635/15598315/96327510-238d-11e6-8f53-62ae4466f544.jpg)
![img_1171](https://cloud.githubusercontent.com/assets/261635/15598313/96321282-238d-11e6-9510-2c10cc04a234.jpg)

**Comment by msimerson** [comment]
### energy meter

<img width="954" alt="energy meter" src="https://cloud.githubusercontent.com/assets/261635/15599188/3f5c601c-2396-11e6-9300-80f7b0b37efe.png">

The green **line** is solar production, the green **area** is solar delivered to the grid. The huge red spikes in the evening is the Nissan Leaf arriving home and getting plugged in.

The graph is showing three typical grey May days. Soon, the grey will clear and the production line will rise to the systems peak capacity. Then our production will greatly exceed our consumption for at least the rest of the summer.

**Comment by msimerson** [comment]
### cloudy -vs- sunny

Enquiring minds keep asking, "Solar in Seattle?"  In this image are 5 cloudy (ranging from mostly-to-entirely) May days followed by one day of full sun and a mostly sunny day with late afternoon haze.

![partly cloudy vs mostly sunny](https://cloud.githubusercontent.com/assets/261635/15698586/de481936-277a-11e6-9c69-aa1a6b17ee4a.png)

The takeaway is that on cloudy days, a 10kW system can can produce more electricity than our house and car uses. On a sunny day, it produces considerably more.

**Comment by msimerson** [comment]
### solar panels
- [iTek IT 290 HE](https://github.com/user-attachments/files/15917454/2016.05.30.SIMERSON.Electronic.O.M.dragged.pdf)
- 12 panels facing East, 22 facing West
- cells: 60
- efficiency: 17.3%
- Type: Mono PERC
- Size: 65.9" x 35.4"
- Vmp: 32.6V, Voc: 39.5V

Itek was acquired by Silfab Solar in 2019.

### inverter

- [Solectria PVI 7600TL](https://github.com/user-attachments/files/15917550/2016.05.30.SIMERSON.Electronic.O.M.dragged.pdf)
  - grid tied
  - type: single phase, transformer less
  - array: grounded

**Comment by msimerson** [comment]
Mid-2017 Update.

With a full year of electric production and consumption measured, and rate updates for 2017 and 2018 known, I have updated my estimates. The Net Metering benefit has substantially increased due to:

1. Seattle City Light electric rates are higher in Shoreline than Seattle.
2. The 2017 and 2018 rate increases are 5.6% (estimated at 4%)
3. An added RSA surcharge of 1.5% on electric bills
4. The coldest winter in 32 years
5. More electricity use than I predicted.
    - I was still adding insulation to the house deep into the heating season.
    - I guesstimated the kWh it would require to heat a 1955 house with heat pumps.
    - I installed a fast (level 2) charger for our Leaf. We were able to use it more, offsetting gasoline with electricity.
6. The increased usage is all at the higher 0.14¢ price tier.

Reasons 1-4 weren't known during my initial estimates. Reasons 5 and 6 were planned but their scale was unknown. I knew I'd be removing all natural gas appliances (furnace, water heater, fireplace) but I hadn't yet decided whether to install tankless electric or a heat pump water heater. I hadn't chosen the heat pumps for house heat yet so I didn't know their HSPF. I also didn't know how much more we'd be able to use the Leaf.

The net result is that I now estimate a 100% return on the solar array in the 6th year instead of the 8th year. Instead of a lifetime gain of ~$40,000 I now expect a profit in excess of $50,000.

### Notes
* I did not include the cost of the heat pumps or the heat pump water heater. Those were efficiency upgrades that I'd have done anyway. If I were keeping natural gas, I'd have replaced the old 80% furnace with a 97% modulating furnace and the "well past it's expected lifespan" gas water heater with a gas tankless. In both cases the costs are comparable and just like replacing the fridge, the efficiency increases have their own ROI schedule.

**Comment by msimerson** [comment]
2018-01-01 Update: [Net Zero Mission Accomplished](https://matt.simerson.net/2018/01/01/net-zero-accomplished/)

**Comment by msimerson** [comment]
I just received my 2018 production incentive payment notice. When the check arrives (before Dec. 15th), we'll have recovered 2/3 of the cost of the array before the end of the 3rd calendar year. I now project recouping 100% of the array cost at the end of the 5th year.

**Comment by msimerson** [comment]
Updated SCL rate increases. The projected increases for future years is 4% per year. The actual increases as approved by the City Council are:

|2019|2020|2021|2022|2023|2024|Average|
|----|----|----|----|----|----|----|
|5.8%|5.4%|3.6%|3.9%|4.0%|4.2%|4.5%|

With future rate increases averaging more than 4% per year, the payback period will be sooner, sometime in the 5th year.

**Comment by msimerson** [comment]
My inverter died on Aug 5th. On Aug 14th I noticed. The breaker had tripped and when I flipped it back on, the inverter would arc and pop and trip it again. I called _Northwest Wind & Solar_ and the next day they came and swapped it out.

**Comment by msimerson** [comment]
- 2020-07-27: inverter throwing errors
- 2020-07-28: Inverter offline again
- 2020-07-29: Inverter offline again
- 2021-04-13: Errors 402, 442, 433, 471
- 2021-04-17 - one brief fault
- 2021-04-18 - Offline 90% of the day
- 2021-04-19 - Offline 20% of the day
- 2021-04-20 - offline 2/3 of the day
- 2021-05-11 - still waiting for inverter replacement
- 2021-05-27 - 2nd visit from NW W&S (Hector)
- 2021-06-03 - installed my own inverter
- 2021-?? - 2nd replacement inverter from NW W&S
- 2022: arc fault in disconnect box
- 2023: 2nd inverter failed, replaced with mine.
- 2024-07: moved solar panels to enphase microinverters on SW roof
- 2024-10: moved solar panels back to North roof

**Comment by msimerson** [comment]
# Solar Production & Consumption History

<img width="444" alt="Image" src="https://github.com/user-attachments/assets/c0649e3a-7ab3-45ae-8af8-da44420e6423" />
