### ISSUE TITLE
electrical system upgrades & capacity planning

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#15]
### present electrical system
- SFR built in 1952. Addition & garage added in 197_.
- 200 amp main service panel located in front of house.
  - Upgraded to 200 amp with 1970s addition
  - 12 open breaker slots
- 100 amp subpanel in the garage, on the wall adjoining the house
  - ~65' from service panel
  - 7 open breakers
  - 2? gage braided aluminum wire in plastic conduit.
- 125 amp subpanel in the crawl space #48
  - 4 tandem breakers (4x 15a, 4x 20a)
  - 4 open breaker slots
- Branch circuits are copper. Both feeders are braided aluminum. Yes, they have antioxidant paste.
### near term electrical forecast
- [x] get [permit](http://www.lni.wa.gov/TradesLicensing/Electrical/FeePermInsp/PermitInspect/GetPermit.asp) (expires May 10, 2017)
- [x] request inspection within 3 days of completion or 1 day after energized
- [x] microwave (12 gage wire, 15A breaker, issue #38)
- [x] solar panels (40A breaker) #13
  - [x] inspection
- [x] car charger in garage #51
- [x] heat pump water heater (20A circuit?)
- [x] two mini split heat pumps
  - two 220V 15A runs to [main / crawl /  garage] panel
  - dependent on outdoor unit siting
- [x] remove unused hot tub wiring #50
- [x] fridge circuit
- [x] dishwasher circuit
### anticipated future changes
- car charger 2 in garage (40A)
- attic rooms, light circuit (15A)
- attic rooms, outlets (20A)
### anticipated peak garage loads
- 32A car charger (usually evenings)
- 30A car charger (random usage)
- 40A solar panels (generating during daylight)
### anticipated peak main panel loads
- 15 amp heat pump water heater
- 30 amp - (2) mini-split heat pumps in mid-winter
- 30 amp - oven
- 30 amp - clothes dryer
- 100 amp - garage
### misc todo
- [x] #49 grounding wire not attached to water main
- [x] loose ground strap near water heater

**Comment by msimerson** [comment]
Main panel:

![main panel](https://cloud.githubusercontent.com/assets/261635/14186226/313468ee-f732-11e5-83c7-ea626e456acb.jpg)

**Comment by msimerson** [comment]
Garage subpanel

![garage subpanel](https://cloud.githubusercontent.com/assets/261635/14186381/f9046b30-f732-11e5-8431-36a3f10696d1.jpg)

**Comment by msimerson** [comment]
### for inspection #1 

* [ ] crawl space subpanel
    * [ ] Bonding screw?
* [ ] office outlet
* [ ] microwave outlet
* [ ] Car charging outlet
