### ISSUE TITLE
walls have no insulation

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#16]
### information
- walls have 3.5" cavities
- [INSULATION](https://github.com/msimerson/330-NE-193rd-St/blob/master/INSULATION.md)
### procure materials
- [x] buy 3" polyiso foam board insulation (#37)
  - [x] wrap foam board in Tyvek to protect it ($160)
- [x] buy furring strips for nailers
  - (314) 8' long 1x3 or 1x4
  - (20) 3/4" 4x8' plywood
- [x] buy screws, qty estimate: 1548
  - ~~[9" Wind Lock SIP Screws](http://www.wind-lock.com/en-us/product/w-sip009/9in-sip-fastener-250-box.aspx), $0.81 ea.~~
  - [9" Dekfast SIP screws](http://www.bestmaterials.com/detail.aspx?ID=16720), $0.35 ea.
  - ~~[Trufast](http://www.trufast.com/products/sip_nail/index.html)~~
  - ~~[9" Headlok Panel screws](http://www.loghomestore.com/1748-headlok-panel-fasteners-9-to-18-inch.php), $0.56 ea.~~
- [x] buy new windows (#8)
- [x] buy house wrap: (2) 9'x150' rolls, $217 @ Lowes
- [x] have z-channel fabricated (300')
- [x] buy insect screening
### insulate cavity
- [x] choose type (see options) (choice: dense-pack cellulose)
- ~~hire contractor to dense pack the walls~~
  - get 3 bids
    - [x] Arrow Insulation
    - [x] Classic Pest Control & Insulation
  - select contractor
  - schedule job
- inspect & verify
### walls todo
- [x] house wall north #93
- [x] house wall east #94
- [x] house wall south #95 
- [x] house wall west #96 
- [x] great room wall east #92
- [x] great room wall west #97
- [x] garage walls #4 

### wall cavity options

| type | R-value | Material | Installed |
| --- | --: | --: | --: |
| dense-packed cellulose | 13 | $950 | $2,500 |
| closed cell spray foam | 24 | $7,000 |  |
### References
- Department of Energy [recommends](https://www.energystar.gov/index.cfm?c=home_sealing.hm_improvement_insulation_table):
  - "Uninsulated wood-frame wall: Drill holes in the sheathing and blow insulation into the empty wall cavity before installing the new siding, and add R5 or R6 insulative wall sheathing beneath the new siding"
- [How to Install Rigid Foam Sheeting](http://www.greenbuildingadvisor.com/blogs/dept/musings/how-install-rigid-foam-sheathing)
- [How to Install Rigid Foam Insulation Outside a House](http://www.greenbuildingadvisor.com/video-how-install-rigid-foam-insulation-outside-house)
- no siding is waterproof
  - provide paths for water to drain down and out
- Avoid reverse laps - higher layers always overlap lower layers

**Comment by msimerson** [comment]
note: since I added R-36 to the exterior of the walls (outside the sheathing), the additional insulation possible in the stud cavities turned out not be necessary. It could still be done, but the ROI is vanishingly low.
