### ISSUE TITLE
two South roofs are aged

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#18]
### description
- torchdown roof is older and springy
- roof is nearing its end-of-life
### todo
- [x] get professional assessment of torchdown membrane's useful life remaining
- [x] get structural assessment of roof (sufficient for solar panel weight?)
- [x] depends on #19 (remove chimney)
### Goals
- Ceiling insulation: R-60. Eventually.
- Solar panels (#13). Roof should outlast solar panels (30+ years)
- To outlive the solar panels, all options (below) share a common above-the-water-control-layer plan: lay 5 inches of poly iso foam (R-30), taped with staggered seams, and covered with standing seam steel roofing.
  - steel roof is stronger, lighter, 100% recyclable, and will last much longer.
### new roofing options
1. Embrace and Extend. Leave the decking and torchdown in place. Overframe the existing roof putting it within the thermal envelope. Add R-30 (fiberglass / rock wool / whatever) batts between rafters. Install new decking, water control layer, poly iso insulation board, and metal roofing.
2. Marshmallow Wedgie - Tear off decking & torchdown. Spray the ceiling with 1-2" of closed cell foam insulation (air seal). Lay down thicker 5/8" decking (partially). Climb into the cavity and spray foam the underside of the new decking (and framing) with 2" of ccSPF. Fill the cavity with (open cell foam, cellulose, mineral wool, fiberglass, etc..), lay the last of the decking, spray foam the underside of it and add the water control layer, insulation boards and metal roof.
   - the spray foam would add rigidity
3. Same as #2 but don't tear off. Open a gable end, shimmy in there with a spray foam hose and fill it up.
   - Depends on length of useful life remaining.
   - can be done incrementally (insulate this year, replace decking & roof later)
4. Pop Top. Tear off existing roofs and demolish ceiling. Add attic trusses and a new steel roof as above. Insulate with 2" of ccSPF under decking. Install wiring, drywall the new ceiling, and finish off new attic rooms as time and budget permits.
   - adds up to 600 sf of living space in attic (est. value: $75,000)
     - attic room [built-in idea](http://www.houzz.com/photos/1176218/Bonus-Room-Guest-Room-traditional-kids-raleigh)
   - aligning the roof slopes improves home appearance (see #2)

Options 1-3 do not disrupt the existing living space.
### solar considerations
- [x] use [PVWatts](http://pvwatts.nrel.gov) to choose optimal title and orientation
  - South @ 35°
  - West @ 10°
- ~~optimum [tilt angle](http://solarpaneltilt.com) is 39.4° (latitude x 0.76 + 3.1°)~~
- 8:12 pitch = 34°, 9:12 pitch = 37° and 10:12 pitch = 40°
  - choosing an 8:12 vs 10:12 pitch reduces solar collection by 2%
### see also

[Roofing](https://github.com/msimerson/330-NE-193rd-St/blob/master/ROOFING.md)

**Comment by msimerson** [comment]
In 2-3 years, paint over the entire roof with an elastomeric coating.

**Comment by msimerson** [comment]
Done. In the fall of 2018 I covered both roofs with Henry TropiCool 100% Silicone roof coating.

**Comment by msimerson** [comment]
Ceiling insulation goal of R-60 was nearly met with about R-50. While I had the inside ceiling removed, I stripped and cleaned the roof decking from below. The roof was springy because it was 1/2" plywood on 24" center rafters. After 61 years it was still in good shape. We switched from a drop to a cathedral ceiling. Before hanging new drywall, I filled the 7.5" rafter bays with closed cell spray foam insulation. I also added 1.5x3" horizontal furring strips perpendicular to the rafters on 16" centers, to hang the drywall from. At R-6.5/in, the spray foam added about R-49. That's a substantial improvement over the 2" of rockwool (~R-10) there previously. It also greatly stiffened up the roof decking. There's no more springiness when walking across it.
