### ISSUE TITLE
has a brick chimney

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#19]
A brick chimney is another way to describe a hole in a roof that sucks warm air out of the house.
### issue
- chimneys are holes in a roof. Holes in roofs **always** leak, eventually.
- roof protrusions cost real money when re-roofing
- brick is a poor insulator
- chimneys are fantastic carcinogen collectors
- chimneys are anachronisms
### used by
- gas furnace (#3)
- gas fireplace
- gas water heater (#46)
### todo
- [x] remove chimney
  - [x] depends on replacement of gas furnace (#3)
  - [x] depends on water heater change (#46)
- [x] remove fireplace
- [x] temporarily patch hole in roof
### history

In the old days, brick chimneys were a great idea. You could burn wood or coal in them, they'd heat up the house as well as the brick. The high thermal mass of the brick would absorb much of the heat and continue radiating the heat into the home long after the fire went out.

The problem with chimneys is that the vast majority of the heat get sucked up the chimney. That didn't matter when the continent was covered with old growth timber and houses were few and far between. Today it matters. Adding glass doors helps, but a traditional fireplace is still horrifically inefficient.

New high-efficiency natural gas burning fireplace inserts are highly efficient and no longer require a chimney. Newer heat pumps are even more efficient and require no fossil fuels.

**Comment by msimerson** [comment]
### update

half removed on July 2.

![13600239_1224091124289446_4361226158472207079_n](https://cloud.githubusercontent.com/assets/261635/16664824/c3143680-4436-11e6-9ed7-35c53febfd22.jpg)

a new hole in the roof

![img_0022](https://cloud.githubusercontent.com/assets/261635/17579094/3dba7316-5f46-11e6-93b3-518f0d2a0cbf.jpg)

from inside

![img_0019](https://cloud.githubusercontent.com/assets/261635/17579112/6a13748a-5f46-11e6-9000-ed836714073a.jpg)

Will resume when time permits and cramped hand muscles recover from swinging a 5# sledge most of a day.

**Comment by msimerson** [comment]
### I'm shrinking, I'm shrinking!

![img_1263](https://cloud.githubusercontent.com/assets/261635/16664908/22479138-4437-11e6-9f8d-d6446372e67f.jpg)
![img_1261](https://cloud.githubusercontent.com/assets/261635/16664909/2267ebd6-4437-11e6-97c6-36addc8d8313.jpg)

**Comment by msimerson** [comment]
### July 7th

![img_1266](https://cloud.githubusercontent.com/assets/261635/16775978/fe012282-4817-11e6-85fb-6d8dd7568097.jpg)
