### ISSUE TITLE
insulate and pour concrete crawl space floor

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#23]
### info
- dirt floor covered with black plastic (moisture & radon control)
  - seams _not_ taped
- there are two dirt levels (~30" variance)
- partially insulated duct work
- no insulation on ceiling (effectively "conditioned" space)
- concrete pad in center supporting chimney (see also #19)
- unvented
- mechanical equipment is already located here (necessitating that it remain conditioned)
- plumbing is located here, mandating that it be kept warm.
- 23' x 26'
### materials
- [x] 6 yards of pea gravel
  - sky nursery: $47/yard @ 10 yards
  - pacific topsoil: $44/yard @ 10, $51.75 @ 6  (total w/tax: $340)
- [x] 20 sheets of 2" XPS foam board insulation ($32 ea)
- [x] 74 feet of perforated drain pipe
- [x] 7 sheets of 3/4 plywood to build concrete forms ($23/ea)
- [x] 6-mil polyethylene
### TODO
- [x] clear out the space (#3 gas furnace, racks, benches, concrete blocks)
- [x] remove furnace ductwork (anticipating subsequent ductless heat pumps)
- [x] dig out 9" of dirt all around ($400)
  - [x] dig out 4" around chimney pad (July 4th) $200
  - [x] dig out 6" all around (July 8th) $175
- [x] remove the chimney (#19)
- [x] remove chimney foundation (July 8th) $175
- [x] dig drainage channel along footings and future interior walls
- [x] install drain pipes along footings, connected to existing drain & sump
  - [x] filter fabric, pea gravel, drain pipe, more stone, filter fabric (a drain pipe "burrito")
- [x] level and grade the dirt (two heights)
  - sloping (1/4" per foot) toward the drain
- install sub-slab layers
  - [x] install drainage pad and capillary break (3-4" pea gravel) (Jul 13)
    - vented to exterior
  - [x] insulation board on grade (Jul 18)
  - [x] insulation board around perimeter wall
  - [x] air/vapor/moisture barrier (polyethylene) (Jul 27)
- [x] lay rebar (Jul 29-30)
- [x] build forms (Aug ~10)
- [x] pour concrete slab (Aug 16)
### thoughts
- Mold, mildew, and dust mites don't colonize dry areas
- Warm dry basements:
  - attract fewer pests and insects.
  - are great for storage
- Insulating the floor above the space [is a bad idea](http://buildingscience.com/documents/insights/bsi-009-new-light-in-crawlspaces).
- Heating this space will provide a warm floor above it.
- the walls need at least R-15 (Marine Zone 4)
### references
- [greenbuildingadvisor: building unvented crawl space](http://www.greenbuildingadvisor.com/blogs/dept/musings/building-unvented-crawl-space)
- [building science: new light in crawl spaces](http://buildingscience.com/documents/insights/bsi-009-new-light-in-crawlspaces)
- [gba: fixing wet basements](http://www.greenbuildingadvisor.com/blogs/dept/musings/fixing-wet-basement)

**Comment by msimerson** [comment]
depends on #80 

Before:

![img_1196](https://user-images.githubusercontent.com/261635/32902301-dfa3abe4-caa6-11e7-9b51-69fc7b8f7a36.jpg)

**Comment by msimerson** [comment]
Filter fabric and drain pipe laid. Now it's ready for gravel, which arrives tomorrow.

![img_1289](https://cloud.githubusercontent.com/assets/261635/16829458/3672829c-494d-11e6-8029-096fd618761f.jpg)

**Comment by msimerson** [comment]
### gravel layer

July 14:

![img_1292](https://cloud.githubusercontent.com/assets/261635/16961795/e4614bcc-4da3-11e6-8095-41af4174b2c0.jpg)

After wheelbarrow conveyance into the crawl:

![img_1293](https://cloud.githubusercontent.com/assets/261635/16961821/ff28f1f8-4da3-11e6-8d5b-3bd51cae5ca0.jpg)

**Comment by msimerson** [comment]
### sub-slab insulation

![img_1294](https://cloud.githubusercontent.com/assets/261635/16961858/297e71ee-4da4-11e6-8efb-cf75ddc4eca0.jpg)

**Comment by msimerson** [comment]
Poured and finished

![img_1372](https://cloud.githubusercontent.com/assets/261635/17723015/71dc7cda-63eb-11e6-9f10-1b4f1655a64e.jpg)

finishing touch

![img_1377](https://cloud.githubusercontent.com/assets/261635/17723020/7e652330-63eb-11e6-8e1c-e5bb0a3e9720.jpg)

**Comment by msimerson** [comment]
### Digging Cost

- Quote from Excavators NW:  min $3,500/day + concrete + 10 yard dumpster
- purchased a dehumidifier 
- most dug with a pickaxe, shoves, and 5-gallon buckets
- disposed of dirt in front yard (filing & leveling it)
- Contract day labor, "El Burro" to shovel and haul dirt with me

### Concrete Costs

- Rebar: $250
- Ralph's Concrete pumping: $1,142.22
- Cement vibrator: $50.59
- Cemex, 18 yards:  $2120.77
