### ISSUE TITLE
crawl space #2 seismic upgrades

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#24]
### status
- sill plate to foundation wall attachment
  - foundation bolts present but insufficient: too few, washers too small, visible rust
- rim joist is not attached to top of the wall (above cripple walls) with metal connectors
- posts lack metal caps attaching them to floor beams
- posts lack post bases attaching them to their foundations
### todo for crawl space 2
- [ ] attach cripple walls to rim joist with A35 framing angles (__pcs @ $0.90 = $)
  - every 16 inches
- [ ] attach interior columns to the floor beams with 24 x AC4 metal post caps
- [ ] attach sill to rim joist with L70 L-angle clips (20 pcs @ $2)
- [ ] reinforce cripple walls bracing (1-2 places on each wall)
  - [ ] double studs
  - [ ] holddowns
  - [ ] mudsill blocking
  - [ ] plywood with vent holes
### references
- [Earthquake Safety](http://www.earthquakesafety.com/earthquake-retrofitting-faq.html)
- [Protect Your Home with a Basic Seismic Retrofit](http://www.finehomebuilding.com/2011/09/08/protect-your-home-with-a-basic-seismic-retrofit)
- [Simpson Seismic Retrofit Guide](https://embed.widencdn.net/download/ssttoolbox/daokkfyn2v/F-SEISRETRGD12R.pdf?u=ydkg9w)
- [How to Stay Safe When The Big One Comes](http://www.newyorker.com/tech/elements/how-to-stay-safe-when-the-big-one-comes)
### current code
- foundation bolts
  - 5/8" or 3/4" bolts every 6 feet
  - 2 or 3" square galvanized plate washers above sill plate
  - min 9" max 12" from ends of plates

**Comment by msimerson** [comment]
Excerpts from [The Really Big One @ New Yorker](http://www.newyorker.com/magazine/2015/07/20/the-really-big-one):

> In theory, those who are at home when it hits should be safest; it is easy and relatively inexpensive to seismically safeguard a private dwelling. But, lulled into nonchalance by their seemingly benign environment, most people in the Pacific Northwest have not done so. That nonchalance will shatter instantly....
> 
> Houses that are not bolted to their foundations will slide off—or, rather, they will stay put, obeying inertia, while the foundations, together with the rest of the Northwest, jolt westward. Unmoored on the undulating ground, the homes will begin to collapse.
