### ISSUE TITLE
replace toilets with high-efficiency

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#29]
For toilets older than 2004, there's a [$100 rebate](http://www.savingwater.org/Rebates/index.htm?id=toilet#toilet) to upgrade them with this [rebate form](http://www.savingwater.org/cs/groups/public/@spu/@swp/documents/webcontent/04_009426.pdf). After the rebate, the Niagara is only $50.
### toilet ages
- Upstairs: Kohler Wellworth K-4436-BB, 1.2gpf,  (2014)
- Downstairs: Kohler, 1.6gpf, ????
### good options
- Niagara 2-piece 0.8 GPF Ultra-High-Efficiency Single Flush Elongated Toilet Featuring Stealth Technology in White at [Home Depot](http://www.homedepot.com/p/Niagara-2-piece-0-8-GPF-Ultra-High-Efficiency-Single-Flush-Elongated-Toilet-Featuring-Stealth-Technology-in-White-77000WHAI1-N7714-N7717/205611735) ($150) and [amazon](http://www.amazon.com/Niagara-77001WHCO1-Stealth-Toilet-Elongated/dp/B009MY4K1K?ie=UTF8&keywords=niagara%20stealth&qid=1461631011&ref_=sr_1_1&sr=8-1) ($247)
- Toto Ultramax II at [amazon](http://www.amazon.com/MS604114CEFG-01-Ultramax-Elongated-Sanagloss/dp/B001BYS5RE/) ($418)
- Toto Drake at [amazon](http://www.amazon.com/CST744SG-01-2-Piece-Elongated-Sanagloss/dp/B0012HBQK8/ref=sr_1_8) ($326)
### TODO
- [x] buy new toilet (May 2, 2016)
- [x] buy new bidet seat
- [x] install new toilet & seat
- [x] submit completed rebate form
  - [x] with receipt
  - [x] with copy of water bill
- [x] receive and deposit rebate check
