### ISSUE TITLE
gas furnace is 80% efficient

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#3]
Which means it's wasting 20% of the gas paid for.
## options
1. replace with high efficiency (95%) gas furnace
   - pros
     - ductwork already in place
     - highly efficient (wastes 15% less)
     - natural gas is (currently) a cheap fuel
     - 95% efficient Trane at Second Use is only $600
     - PSE rebates
   - cons
     - fossil fuel
     - natural gas price is more volatile than electricity
     - requires connection fees, even in summer months when no gas is used
     - leaks are far too common, resulting in poisonings and explosions
         - much higher risk in seismically active areas
2. replace with mini-split heat pumps (#53)
   - pros
     - new models are super-efficient (HSPF 10+) and heat well, even in winter
     - we don't use A/C much in Seattle, but 20+ SEER is a nice perk.
     - Seattle has cheap green electricity
     - uses no fossil fuels (Seattle's grid power is mostly hydro plus some wind, solar, and other)
     - pairs well with solar panels (#13)
     - zoned heating
   - cons
     - requires 220v wiring
     - higher install cost than a replacement furnace
### todo
- [x] remove ducts from crawl space
- [x] remove furnace from crawl space
- [x] install heat pumps (#53)
