### ISSUE TITLE
west windows overheat the family room

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#32]
# todo
- [x] unpack window film
- [x] find and unpack spray bottle
- [x] apply window film
- [ ] install solar screening #42
