### ISSUE TITLE
GU24 light fixtures

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#34]
### cons
- require non-standard ($$$) bulbs
- are currently loaded with non-dimmable CFLs
- new fixtures cost less than LED bulb replacements
### TODO
- [x] buy new fixtures
- replace fixtures
  - [x] upstairs hallway
  - [x] foyer (2x low)
  - [x] dining room
- install LED bulbs
  - [x] upstairs hallway (2x low)
  - [x] foyer (2x low)
  - [x] dining room (2x low)

**Comment by msimerson** [comment]
related to #9
