### ISSUE TITLE
dispose of old fridge & freezer in garage

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#35]
### issues
- they are old
- they are inefficient
- [SCL will haul them away and give me $30](http://www.seattle.gov/light/conserve/resident/appliances/cv5_appA2.htm)
### todo
- [x] schedule pickup (May 17th)
- [x] plugin in a day before to prove they are working
- [x] Kenmore Upright Freezer, 253.29401990, serial WB01721702, 13.8 cf., Mfd 4-00, 811 KWH/yr
- [x] White Westinghouse Fridge/Freezer, Model MRT15CSCW4, 15.4 cf., Mfd 02-96, 702 KWH/yr
- [x] collect & deposit rebate (Jun 11)

**Comment by msimerson** [comment]
```
Date: Tue, 31 May 2016 18:06:56 -0500 (CDT)
Subject: Appliance Recycling Incentive/Rebate Processed

Dear MATT, 

Congratulations and thank you for your participation in the Seattle City Light Refrigerator Recycling Rebate Program. Your incentive/rebate has been processed and is expected to mail within the next 7 business days.

Thank you for participating in the program.

Sincerely,
Your Local Utility's Contracted Incentive/Rebate Processor


You will be unable to reply to this email because it has been automatically generated. You have not been added to an email list.
```
