### ISSUE TITLE
no microwave

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#38]
### details
- existing over-the-range height is 30" (too short for an over-the-range micro)
- existing range hood is an unusually large 42" wide
- limited counter space
- over-the-range would be quieter than the existing jet-engine
### Questions
- range hood or countertop?
- finish: stainless
### TODO
- [x] choose a microwave, [Panasonic NN-SN973S](http://amzn.to/1XlLUHq)
- [x] buy a microwave (May 12)
- [x] install it.
  - [x] run a 12-gage dedicated circuit to it (from #48 subpanel)
    - (I can't find any solid evidence for this but the Home Depot appliance guy (Ernie) tells that most microwaves are "good enough" today. Many that fail (especially if it's the magnetron) are from older homes where the microwave doesn't have sufficient current. A typical 1200 watt microwave draws 11 amps, so putting it on it's own 15A circuit where it won't have to share with a toaster oven or other kitchen appliances seems prudent.
  - 15 amp breaker (can be upgraded to 20A if a future microwave requires it)
- [x] set up an under-counter stand/mount for it
