### ISSUE TITLE
replace washing machine

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#39]
### current washer
- Brand: Kenmore
- Model 110.20022012
- Ser. C14333241
- manufactured in Clyde, OH, ~2000
### todo
- [x] select newer high efficiency model
- [x] purchase washer (May 5)
- [x] hook it up (May 8)
- [x] submit rebate form (May 10)
- [x] deposit rebate (June 16)
