### ISSUE TITLE
garage is not insulated

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#4]
### reasons to fix
1. it overheats in the spring & summer
2. electric resistance heater is highly inefficient
3. higher fire risk due to exposed wood
### todo
- insulate walls
  - [x] north #88 
  - [x] east #89 
  - [x] west #98 
  - [x] south #90
- insulate garage door #52 
- [x] insulate garage ceiling #75
  - [x] 1-2" of ccSPF spray foam #75
  - [ ] fill trusses with batts
  - [x] hang drywall
- [ ] insulate floor or crawl space perimeter walls
### see also

[INSULATION](https://github.com/msimerson/330-NE-193rd-St/blob/master/INSULATION.md)

**Comment by msimerson** [comment]
1” of spray foam was installed. Ceiling is drywalled. Mudding is in progress. Prime and paint will follow.
