### ISSUE TITLE
replace the fridge

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#40]
### status
- GE Fridge/Freezer
- Model TFX24RMA
- 23.6 ft/cu
- Mfd. 06/91
- uses 1,555 KWH/yr
- newer equiv models use 1/3 the energy

General rule of thumb: if the fridge is more than 10 years old, it costs money not to replace it.
### 
- Dimensions: 67.75 H x 36 W x 29+ D.
### todo
- [x] select a new fridge
- [x] buy new fridge
- [x] wire a dedicated circuit #61
- [x] cut out over-fridge cabinet so family-sized fridges fit
- [x] install new fridge
### candidates
- Whirlpool WRF535SMBM, 25.2 cu. ft., 449 KWH/yr ([@ Home Depot](http://www.homedepot.com/p/Whirlpool-25-2-cu-ft-French-Door-Refrigerator-in-Monochromatic-Stainless-Steel-WRF535SMBM/204177400))
- LG LTCS24223S ([@ Home Depot](http://www.homedepot.com/p/LG-Electronics-23-8-cu-ft-Top-Freezer-Refrigerator-in-Stainless-Steel-LTCS24223S/205343837))
### thoughts
- built-in water cooler and ice maker is nice, but not nice when it breaks. A standalone water cooler / heater combo is far more reliable, easy to repair/replace, and cheaper.

**Comment by msimerson** [comment]
### cabinet cut down to size

So the new fridge fits:

![img_1203](https://cloud.githubusercontent.com/assets/261635/15945895/48a97cb4-2e49-11e6-9fae-8521fa4441ac.jpg)
