### ISSUE TITLE
replace the dishwasher

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#44]
### status
- it's really old
- it's really loud
- it's miserable to load/unload
### todo
- [x] select one
  - Kitchenaid KDTM354DSS @ [Sears](http://www.sears.com/kitchenaid-24inch-built-in-dishwasher-w-ultra-fine/p-02214233000P?lid=product_name1&rioptype=&sid=ITx20160513TriggeredRTMSRSShoppingRecapDigitalSignage2HOME_APPL), [HomeDepot](http://www.homedepot.com/p/KitchenAid-Architect-Series-II-Top-Control-Dishwasher-in-Stainless-Steel-with-Stainless-Steel-Tub-Ultra-Fine-Filter-43-dBA-KDTM354DSS/205397273)
- [x] buy
- [x] wire a 20-amp dedicated circuit
- [x] remove old rotten and moldy particle board flooring
- [x] replace flooring with 3/4 plywood
- [x] install new supply line from tee under sink
- [x] install dishwasher

**Comment by msimerson** [comment]
### status

* it's really old
* it's really loud
* it's miserable to load/unload

### todo

* [ ] select
* [ ] buy
* [ ] install

**Comment by msimerson** [comment]
### moldy rotten particle board

Particle board is not a construction material, it's a crime against humanity. Putting it near appliances that have water connections is dumb, dumb, dumb.

![img_1200](https://cloud.githubusercontent.com/assets/261635/15945342/cf243020-2e46-11e6-8344-c82104a9cc45.jpg)
