### ISSUE TITLE
water heater uses chimney

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#46]
### info
- blocks the removal of the chimney (#19)
- existing water heater is 16 years old.
- water heater had 6 year warranty
- it's well past a water heaters typical (8-12 years) service life
- pilot light always burning gas
- eligible for $300 federal tax credit ([GE certification statement](http://www.geappliances.com/ge/heat-pump-hot-water-heater/downloads/2016-geospring-federal-tax-credit-certificate.pdf), [IRS Residential Energy Credits](http://programs.dsireusa.org/system/program/detail/1274))
- no drain pan
### options
- add power venting to this gas heater
- replace with
  - power vented gas heater
  - heat pump water heater ($817.65)
    - ~~[$500 rebate](http://www.seattle.gov/light/conserve/resident/hpwhrebate/) from Seattle City Light~~ (only if replacing electric water heater)
    - bigger tanks, to compensate for longer recovery time
    - 3.25 Energy Factor for GE GeoSpring 50 gallon
  - tankless water heater
    - gas is fast, but would be the only gas appliance.
    - electric uses lots (3 x 40A circuits) of juice
### todo
- [x] buy a heat pump water heater, 2016-06-10, $817.65
- [x] clear out area for new heater
- install new water heater
  - [x] run new branch circuit #66
  - [x] tie two 30A 110 breakers together
  - [x] in a drain pan
  - [x] connect drain pan to sump drain
- [x] run new 3/4" copper pipe
  - [x] - (3) 3/4 elbows
  - [x] - (1) 3/4 tee
  - [x] - (1) 3/4 copper pipe
  - [x] - (2) 3/4 copper couplers
  - [x] - (2) 3/4" pipe caps
### references
- [DIY install tips](https://hotwatersolutionsnw.org/assets/documents/uploads/HWS_DIY_Sheet_FNL_REF.pdf)
- [King County: Installing your new water heater](http://www.kingcounty.gov/healthservices/health/ehs/plumbing/waterheater.aspx)
- [Amtrol ST-12 Thermal Expansion Tank](http://amzn.to/1Ur1Y5J)
### Excerpt from King County

> Expansion tanks
> 
> If your water is on a closed system (the water can flow into your building but not out), an expansion tank or other approved thermal expansion device must be installed on your water system. The expansion tank is to hold water that can't be held in the water heater after it expands when it gets hot. If there were no expansion tank, the hot water would be released through the pressure relief valve.

**Comment by msimerson** [comment]
### front

![water heater front](https://cloud.githubusercontent.com/assets/261635/16607523/b9288dec-42f6-11e6-9cf1-193ed8031f5e.jpg)

### side

![water heater side](https://cloud.githubusercontent.com/assets/261635/16607525/befec57e-42f6-11e6-9b18-dcecc73ede73.jpg)

The strapping isn't on yet attaching it to the wall. That needs to wait until after the insulation is on the wall. Then a framing member will be screwed to the concrete wall (through the insulation) and the straps will mount to that.
