### ISSUE TITLE
kitchen remodel

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#47]
### current issues
- no cookbook storage
- fridge blocks doorway
- scattered work centers (food prep, cooking, baking)
- kitchen located between indoor & outdoor eating areas
- kitchen located in primary foot path
### ideas
- relocate kitchen onto West wall
  - puts both eating areas on the same side (normalized traffic to/from eating areas)
  - puts fridge/pantry next to side door (easier grocery hauling)
  - moves kitchen away from primary traffic areas
  - depends on #19 remove chimney
### todo
- [x] interview kitchen designers / installers
  - [x] [Bob McEwen](http://www.mcewenscabinets.com)
  - [x] Tana
  - [x] Susan Lihudis
- [x] mull ideas, cogitate, discuss
  - [x] coordinate with designer, both household cooks, and design an awesome kitchen
- [x] contract with a kitchen designer
- [x] install it

**Comment by msimerson** [comment]
- [x] buy an induction cooktop
- [x] buy a new electric oven
- [x] dispose of old electric range

**Comment by msimerson** [comment]
### a pex manifold

In preparation for converting the entire house plumbing to PEX, but staged and pre-plumbed so that in one day, all the old plumbing (and old kitchen with it) goes out and the new plumbing and kitchen is "live."

![img_0112](https://user-images.githubusercontent.com/261635/43989688-b52d7a2c-9d03-11e8-9153-408b78bda29f.jpeg)

### plumbers apprentice
![img_0113](https://user-images.githubusercontent.com/261635/43989689-b543dda8-9d03-11e8-8370-3b90bbabc07e.jpeg)

### completed manifold with insulation

![img_0117](https://user-images.githubusercontent.com/261635/43989690-b55df3e6-9d03-11e8-8c24-c984f3f54461.jpeg)

### galley kitchen

Smushed against the east wall while the new kitchen is constructed on the west wall.

![img_0131](https://user-images.githubusercontent.com/261635/43989691-b56e7aea-9d03-11e8-9f0c-e6c74ae5ab56.jpeg)

### cabinets and hood installed

![img_0162](https://user-images.githubusercontent.com/261635/43989692-b57f3e70-9d03-11e8-9884-7dbbae2f0863.jpeg)

### done

![img_0220](https://user-images.githubusercontent.com/261635/43989693-b5900f3e-9d03-11e8-92b7-c82b62357d84.jpeg)
