### ISSUE TITLE
Install electrical subpanel in crawl space

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#48]
### background
- main panel is difficult to access
  - resulting in lots of spaghetti wiring
- installing a subpanel
  - makes future wiring projects much easier
  - allows mutilated corner studs to be repaired
### specs
- 125 amp panel
- 8 breakers (supports 16 tandem breakers)
### todo
- [x] buy Cutler Hammer subpanel (same breakers as existing)
- [x] install subpanel
  - [x] 2-gage feed from main panel
  - [x] mostly (90%) enclosed in conduit
  - [x] fully enclosed in conduit
- [x] install 100A breaker in main panel
- [x] Inspection
  - [x] microwave circuit #38 
  - [x] fridge circuit #61
  - [x] dishwasher circuit #62
  - [x] water heater circuit #46
  - [x] car charger #51
  - [x] crawl space light circuit #59
  - [x] crawl space outlets #60 
  - [x] office outlet

**Comment by msimerson** [comment]
### May 2017

- replaced cute little 8-breaker subpanel with a 24-breaker main panel
    - hired an electrician to do the panel swap
- reasons:
    - Even with dual breakers, I had filled the little subpanel
    - I had additional circuits I wanted to remove from the main and clean up the _corner of disaster_
    - the subpanel box didn't have sufficient horizontal space for combination AFCI/GFCI breakers
    - code now requires AFCI breakers in some rooms

**Comment by msimerson** [comment]
# 2016 Subpanel

![IMG_1197](https://github.com/user-attachments/assets/7d03407c-7ea5-46fb-aebb-37b8e94f58ac)

# 2017 Bigger Subpanel

![IMG_0210](https://github.com/user-attachments/assets/b45213c8-08da-42c4-bcd3-5cf148d14385)

# 2024 Go Big or Go Home Subpanel

Upgrading this subpanel was done (yet again) because:

  - most breakers are now either AFCI, GFCI, or both
  - the 24-space subpanel was full (there's no dual AFCI/GFCI breakers)
  - pigtails are messy
  - the old panel was crowded
  - I wanted to move the garage feed to this subpanel

![IMG_5688](https://github.com/user-attachments/assets/3d1d73a0-149f-4bea-9329-87c1d5fdea72)
