### ISSUE TITLE
has unused wiring for hot tub

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#50]
### todo
- [x] remove wiring from panel
- [x] remove wiring
- [x] remove shutoff switch
- [x] patch hole in wall
  - foam or caulk?

**Comment by msimerson** [comment]
### before

![img_1178](https://cloud.githubusercontent.com/assets/261635/15876768/3c6aa15c-2cc4-11e6-90bf-2f68ad2c0f96.jpg)

### after

![img_1180](https://cloud.githubusercontent.com/assets/261635/15876770/3ff98d9c-2cc4-11e6-9d3d-ead69942fd3e.jpg)
