### ISSUE TITLE
a faster (level 2) car charger would be nice

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#51]
### background
- we just signed our second Nissan Leaf 3-year lease
- 2013 Leaf had 85-mile range, 2016 model has 107 miles
- bigger battery takes longer to fill up
### options
- [ChargePoint 32A Plug Station - $699](http://amzn.to/20Q6jUm)
- [Electric Motor Werks JuiceBox 40A WiFi - $599](http://amzn.to/1sVTdud)
- [Ebusbar 16A - $299](http://amzn.to/1XYA2eP)
### todo
- [x] select a level 2 car charger
- [x] buy the car charger (June 2)
  - [x] file sales tax exemption [form](http://dor.wa.gov/Docs/Forms/ExcsTx/ExmptFrm/BuyersRetailTxExmptCert_E.pdf) with [amazon](https://www.amazon.com/gp/help/customer/display.html?nodeId=201133470)
  - [x] receive sales tax credit (June 3)
- [x] wire a 2-gage circuit to car charging area
  - 115 amp rating will support any future charging needs w/o needing new wire
  - [x] conduit is supported every 10'
  - [x] conduit is supported within _' of terminations
- [x] install a NEMA 6-50 connector
- [x] hook up car charger (June 6)

**Comment by msimerson** [comment]
A Level 2 charger makes a big difference!

![screen shot 2016-06-09 at 9 18 01 am](https://cloud.githubusercontent.com/assets/261635/15937543/3b1867ba-2e24-11e6-9699-2c6247aafa15.png)

**Comment by msimerson** [comment]
Earlier this summer I relocated the ChargePoint from the garage to the carport. We typically park under the carport and have been using the 120V charger there regularly, and then pulling back to the garage as needed. In the place of the ChargePoint in the garage, I dropped a NEMA 14-50 plug, which either cars EVSE can plug into.

### advantages

- all the EV charging now happens on the ChargePoint
    - the ChargePoint meters how much current is drawn, so I can know how much of our electric use was for EV charging. Previously I had to estimate.
- if needed, we can charge both EVs at the same time
    - our older Leafs only came with 120V chargers. The '19 and Tesla both come with NEMA 14-50 plugs for 240V charging

### ChargePoint

![RenderedImage](https://user-images.githubusercontent.com/261635/68731688-cf9a3300-0585-11ea-8e92-a74bcaeb44fb.jpg)


### Old location

![RenderedImage](https://user-images.githubusercontent.com/261635/68731676-c741f800-0585-11ea-9693-293735c70f58.jpg)

![58982351565](https://user-images.githubusercontent.com/261635/68731848-4cc5a800-0586-11ea-835d-960d6d96a2d0.jpg)
