### ISSUE TITLE
garage attic needs cleaning

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#54]
### info
- coated in a thick layer of dust
- has old cabinets stored there
- has piles of scrap wood (cut ends of various lumber)
- spare shingles
### todo
- [x] clear out scrap lumber
- [x] remove cabinets
- [x] vacuum dust off floor and walls
- [x] move shingles to garage crawl space
- [x] paint floor and walls white (interior latex)
-  wire in another light bulb (or two) #65

**Comment by msimerson** [comment]
![img_1245](https://cloud.githubusercontent.com/assets/261635/16608166/02c502e4-42fe-11e6-82e1-b92c54e9b4ac.jpg)
![img_1240](https://cloud.githubusercontent.com/assets/261635/16608165/02c36b50-42fe-11e6-926c-8a64718117f8.jpg)
![img_1241](https://cloud.githubusercontent.com/assets/261635/16608164/02c1a5b8-42fe-11e6-99bb-02c719a96efe.jpg)
