### ISSUE TITLE
shopping list

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#56]
A running "to buy" list

### now

- lap siding for window sills ( feet)

### soon

- #24 seismic upgrades
  - [ ] Simpson L70 reinforcing L-angles, 20 @ $1.78 @ H.D.

### eventually

- #87 Imazapyr (herbicide)
- #52 garage door insulation
  - [ ] styrofoam insulation, 1.5" x 4' x 8', 7 @ $16.25 @ HD

### completed

- #26 finish basement as master suite
  - [x] XPS insulation: O.C. 2" x 4' x 8', 19 @ $31
- #24 seismic upgrades
  - [x] Simpson A35 framing angles, 20 @ $0.90 @ HD
  - [x] Simpson 5/8" x 2.5" x 2.5" bearing plates, 12 @ 2.64 @ HD
  - [x] Simpson AC6 post caps, 4 @ 5.85 @ HD
  - [x] Simpson AC4 post caps, 6 @ 4.29 @ HD
  - [x] Simpson Titen HD 1/2" x 5" HD anchor screws, 2 (40) @ 75.66 @ HD
  - [x] Simpson UFP10 universal foundation plates, 20 @ $15.74 @ HD
- [x] dehumidifer
- #23 crawl space floor
  - [x] 566 sf. of thick (6+ mil) plastic for floor vapor barrier
  - [x] XPS foam insulation: Owens Corning 2" x 4' x 8', 19 @ $31.22 @ HD
  - [x] 3/4 or 1" plywood for poured walls, 7 @ $30
- siding
  - [x] #16 furring strips
  - [x] house wrap
- [x] windows (plygem vinyl) ($6,789)
- [x] 1000 x 9" long screws #16 ($405)
- [x] great stuff pro wall & floor adhesive 26.5 oz, 3 @ $17.48 for #52 and #22 and #16 
- [x] 1200 sf. of ccSPF insulation ($1,429)
- [x] 2 x AFCI circuit breaker
- [x] 2 x GFCI circuit breaker
- [x] 1 x AFCI/GFCI combination circuit breaker
- [x] 10-2 electrical wire, 50'
- [x] 1-gang GFCI wall plate, white, 4 @ 0.65 @ HD
- [x] heat pump water heater #46
- [x] tamper resistant outlets, 10-pack, white, $11
- [x] light box outlet blank cover #67
- [x] 15-amp GFCI outlet, 3-pack, white, $33
- [x] 20-amp GFCI outlets, 3-pack, white, $39

**Comment by msimerson** [comment]
* #26 finish basement as master suite
    * [x] XPS insulation: O.C. 2" x 4' x 8', 19 @ $31
* #24 seismic upgrades
    * [x] Simpson A35 framing angles, 20 @ $0.90 @ HD
    * [x] Simpson 5/8" x 2.5" x 2.5" bearing plates, 12 @ 2.64 @ HD
    * [x] Simpson AC6 post caps, 4 @ 5.85 @ HD
    * [x] Simpson AC4 post caps, 6 @ 4.29 @ HD
    * [x] Simpson Titen HD 1/2" x 5" HD anchor screws, 2 (40) @ 75.66 @ HD
    * [x] Simpson UFP10 universal foundation plates, 20 @ $15.74 @ HD

* [x] dehumidifer
* #23 crawl space floor
    * [x] 566 sf. of thick (6+ mil) plastic for floor vapor barrier
    * [x] XPS foam insulation: Owens Corning 2" x 4' x 8', 19 @ $31.22 @ HD
    * [x] 3/4 or 1" plywood for poured walls, 7 @ $30
* siding
    * [x] #16 furring strips
    * [x] house wrap
* [x] windows (plygem vinyl) ($6,789)
* [x] 1000 x 9" long screws #16 ($405)
* [x] great stuff pro wall & floor adhesive 26.5 oz, 3 @ $17.48 for #52 and #22 and #16 
* [x] 1200 sf. of ccSPF insulation ($1,429)
* [x] 2 x AFCI circuit breaker
* [x] 2 x GFCI circuit breaker
* [x] 1 x AFCI/GFCI combination circuit breaker
* [x] 10-2 electrical wire, 50'
* [x] 1-gang GFCI wall plate, white, 4 @ 0.65 @ HD
* [x] heat pump water heater #46
* [x] tamper resistant outlets, 10-pack, white, $11
* [x] light box outlet blank cover #67
* [x] 15-amp GFCI outlet, 3-pack, white, $33
* [x] 20-amp GFCI outlets, 3-pack, white, $39
