### ISSUE TITLE
crawl space is dreary and poorly lit

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#59]
### issues
- light bulb mounted at a "can walk into it" height
- ancient fluorescent fixtures & bulbs
- not nearly enough light
- spaghetti wiring
### todo
- [x] run a new light circuit with 5 switched outlets
- [x] upgrade fluorescent fixtures with LED bulbs
- [x] mount new fixtures between the joists, out of the walking space

**Comment by msimerson** [comment]
### before

![img_0960](https://user-images.githubusercontent.com/261635/43989268-b82fee92-9cfb-11e8-8a01-2d62ab111480.jpeg)
![img_0959](https://user-images.githubusercontent.com/261635/43989269-b84003fe-9cfb-11e8-9085-0bd34c8b4c18.jpeg)


### let there be light!

![img_1196](https://cloud.githubusercontent.com/assets/261635/15877709/64422744-2cca-11e6-82d6-941899212cd2.jpg)
![img_1197](https://cloud.githubusercontent.com/assets/261635/15877710/6460223a-2cca-11e6-82ae-45604d4facaf.jpg)
