### ISSUE TITLE
only two outlets in crawl space

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#60]
### issue
- only two continuously powered outlets in crawl space
- resulted in lots of extension cords all over
### todo
- [x] wire in a new GFCI (basement) circuit
- [x] with outlets spaced along the floor support beam
- [x] so power tools, shop vacs, and sump pumps all have a near outlet
