### ISSUE TITLE
fridge needs a dedicated circuit

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#61]
### issue
- you don't want the fridge breaker to trip. Ever.
- put it on a dedicated circuit
- which happens to be code now
- existing circuit is ungrounded (1958)
### todo
- [x] add a 12-ga branch from the crawl subpanel
- [x] replace existing 12-ga branch for the other kitchen outlets
- [x] replace broken outlet
- [x] rewire polarity reversed outlet
- [x] wire up the ground wires in two kitchen outlets (the wiring in the walls was replaced with grounded wire, but the branch feeding them wasn't.)
