### ISSUE TITLE
dishwasher needs a dedicated circuit

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#62]
### description
- dishwashers can draw a surprising amount of current (~12 amps)
- put them on a dedicated circuit
### todo
- [x] run a 20-amp (12-ga) branch to dishwasher
  - [x] update feed to garbage disposal, also on that circuit
- [x] install GFCI outlet
