### ISSUE TITLE
dispose of ancient GE fridge

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#64]
### info
-  GE Fridge/Freezer, TFX24RMA, 23.6 cf, 1991, 1,555 KWH/yr
### issues
- it is old and not efficient
- a new fridge will pay for itself in a few years with reduced energy use
- option: post on Freecycle / craigslist (perpetuate excessive utility costs on others? nah)
### todo
- [ ] [Shoreline Transfer Station](http://your.kingcounty.gov/solidwaste/facilities/shoreline-transfer.asp?ID=346#fees) $30
  - [ ] [$50 rebate for replace & recycle](http://www.seattle.gov/light/conserve/resident/fridgerebate/docs/Fridge_Rebate.pdf)
- [x] post on craigslist

**Comment by msimerson** [comment]
Gone. A nice lady came and hauled it away.

**Comment by msimerson** [comment]
![img_1281](https://cloud.githubusercontent.com/assets/261635/16829834/eaac246e-494f-11e6-86a3-9cfceef2ed0e.jpg)
