### ISSUE TITLE
water heater needs branch circuit

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#66]
### info
- ge heat pump water heat
- 220V
- 30 amps
### todo
- [x] buy 45' of 10 ga romex (10-2)
- [x] run wire from panel to new water heater location
- [x] buy a breaker tie bar
- [x]  tie the two 30-amp breakers together
