### ISSUE TITLE
make garage attic into cozy play space

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#68]
The kids have taken a fancy to the garage attic space. There's enough space for my storage totes and for them to have some play area.
### todo
- [x] build rock climbing holds up the post into the attic 
- [x] buy foam floor mats
- [x] buy rock climbing handholds
  - [x] and t-nuts and bolts
- [x] add more climbing holds up the post
- [x] install foam floor mats

**Comment by msimerson** [comment]
![img_0584](https://user-images.githubusercontent.com/261635/47978682-fcaf2e00-e073-11e8-9737-08625ef889de.jpeg)
