### ISSUE TITLE
fossil fuel freedom

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#71]
### background
- most of Seattle's [grid power](http://www.seattle.gov/light/FuelMix/) is already fossil fuel free (hydro 90%, nuclear 4%, wind 4%)
- my 10kW of solar panels boosts that #13
- our Leaf is 100% electric, consuming no fossil fuels
- after The Really Big One, electricity will be working months before the [three thousand miles of natural gas pipelines](http://www.newyorker.com/tech/elements/how-to-stay-safe-when-the-big-one-comes) are restored.
### todo
- [x] replace gas water heater with heat pump water heater #46 
- [x]  replace gas furnace with heat pumps #3 
- [x] replace our Ford Fusion hybrid with an all-electric car

**Comment by msimerson** [comment]
I did some research and from data points provided by the EIA and King County, I was able to assemble this chart which represents the typical household energy consumption by type:

<img width="192" alt="screen shot 2017-05-31 at 10 57 29 pm" src="https://cloud.githubusercontent.com/assets/261635/26666549/6b15ccba-4655-11e7-9074-d91c497f8197.png">

In a given year, the "average" household in my climate uses about 10 MWh of electricity, the equivalent of 11 MWh of natural gas, and the equivalent of 15 MWh of gasoline. The NG is used primarily for home heating, hot water, and sometimes cooking. Gasoline is used solely for transportation. Combined, the three types of energy equate to 36 MWh of energy used.

After replacing the furnace and water heater with electric equivalents, our house no longer has NG and we use very little gasoline. Our household energy consumption now looks like this:

<img width="185" alt="screen shot 2017-05-31 at 10 57 37 pm" src="https://cloud.githubusercontent.com/assets/261635/26666802/c1be1968-4656-11e7-9bd5-89035b7f6e8b.png">

**Comment by msimerson** [comment]
### Fuel Efficiency

My Tesla Model 3 Long Range has an energy capacity that's roughly equivalent of 2 gallons of gasoline yet can still travel 310 miles. 

![IMG_0212](https://user-images.githubusercontent.com/261635/54636001-a51dc780-4a42-11e9-9d3c-a985b14ae8e9.jpg)

![IMG_0214](https://user-images.githubusercontent.com/261635/54635983-9b945f80-4a42-11e9-995c-b750489fc992.jpg)

The Ford Fusion's days are numbered.
