### ISSUE TITLE
insulate garage ceiling with 1" spray foam

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#75]
### garage info
- 31' wide
- 27' 4" deep
- ceiling area: 928 sf.
### todo
- [x] order 1200 sf. spray foam $1,429
- [x] cover area under area to be insulated with plastic
- [x] read [the instructions](http://sprayfoamkit.com/wp-content/uploads/docs/2012%20online%20instructions.pdf)
- [x] spray 1" thick layer of foam
- [x] clean up

**Comment by msimerson** [comment]
Most of the rest of the ceiling was spray foam insulated in July '18, on a nice hot 80° day.
