### ISSUE TITLE
Birds getting into the roof

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#77]
Birds have torn through the screening and are entering the roof. 
### todo
- [x] buy 1/4" wire mesh
- [x] add insect screen, bird screen, and wire mesh
- [x] Clean bird crap off the house wall

**Comment by msimerson** [comment]
### naughty birds

![img_1238](https://cloud.githubusercontent.com/assets/261635/16545858/4b5d5e3e-40ec-11e6-9b77-96bdc79a3905.jpg)

### fixed

![img_1246](https://cloud.githubusercontent.com/assets/261635/16545861/50e79072-40ec-11e6-8305-1f9a61ea86df.jpg)
