### ISSUE TITLE
windows are single pane aluminum framed

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#8]
### issues
- lots of heat leakage (u-factor 1.3, R-1)
- Condensation on the interior glass wets and deteriorates the wood sills.
- aluminum is a great conductor of heat / horrible insulator (reduces to R-0.5)
- glazing needs replacement
### todo
- [x] measure every window needing replacement
  - [x] consider how windows are used, adjust type
  - [x] adjust measurements for new sizes
- [x] get quotes for new windows #74 
- [x] order windows
- [x] wait for delivery (July 13)
- [x] install windows (#76)
- [x] apply for rebate (#101)
### References
- [Efficient Windows Collaborative](http://www.efficientwindows.org)
- [Innie Windows vs Outies: When walls have exterior foam, where do the windows go?](http://www.greenbuildingadvisor.com/blogs/dept/musings/innie-windows-or-outie-windows)
- [Window Installation Tips for a Deep Energy Retrofit](http://www.greenbuildingadvisor.com/blogs/dept/guest-blogs/window-installation-tips-deep-energy-retrofit)

**Comment by msimerson** [comment]
### considerations

* cost of double vs triple
* energy use difference (ROI period?)
* air leakage
* emergency egress
    * minimum dimensions
        * 20" wide, 24" high
        * net clear opening 5.7 sq. ft
    * 44" max sill height
* intruder resistance
* casement and awning windows seal better
* high end vinyl windows are good, any other vinyl is not
* insulated fiberglass frame is most durable and least maintenance.

**Comment by msimerson** [comment]
The last single pane window has been replaced. Happy day!
