### ISSUE TITLE
replace rotted posts that support main floor beam

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#80]
### info
- the posts are untreated and have decay at the bottom where they rest on the concrete footing
- the posts are attached to the beam with 4 toe-nails
- the posts rest on the footings (no attachment)
### materials
- [x] {2} pressure treated 6x6 posts ($53)
- [x] {3} shoring poles ($90)
- [x] {2} Simpson Galvanized 6x6" column base ($40)
- [x] {4} Simpson 6" post cap
- [x] {7} 80# sacks of concrete ($23)
### todo
- [x] set the shoring poles in place
- [x] jack the beam up, transfer load to shoring poles, and lower beam
- [x] remove the existing beams
- [x] build (2) 2' square boxes for new footings (2x8)
- [x] cut the new posts to length
- [x] mount the column bases to the new posts
- [x] using the post caps, suspend the poles from the beam, plumb and level over the boxes for the new footings
- [x] mix 3 bags of concrete and fill the new footings

**Comment by msimerson** [comment]
### before

![img_1255](https://cloud.githubusercontent.com/assets/261635/16793356/3da7c036-4885-11e6-8e66-70ff3ca7f56a.jpg)

The decay in the post is visible here, as is the lack of post caps and anchoring of the post on the footing.

### after

![img_1286](https://cloud.githubusercontent.com/assets/261635/16793361/45c55ecc-4885-11e6-834f-9ab7b6309bf7.jpg)

**Comment by msimerson** [comment]
related to #24
