### ISSUE TITLE
dispose of HUGE pile of bricks and blocks

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#81]
### info
- tearing out the chimney resulted in a huge pile of masonry
- busting up the hearth and chimney foundation  created many chunks of concrete
### todo
- [x] post free ad on craigslist (July 8)
- [x] post free ad on NextDoor
- [x] watch several people come and haul away many bricks (July 9-12)
- [x] re-stack the remaining bricks by type (July 13)
- [x] re-post if necessary (July 25)
- [x] haul remainder of masonry (broken bricks & blocks, mortar, etc..) to neighbors who need fill (Aug 20)

**Comment by msimerson** [comment]
### front of the pile

![img_1267](https://cloud.githubusercontent.com/assets/261635/16793671/8a2f19d4-4887-11e6-9837-d9ed61a483c7.jpg)

### back of the pile

![img_1268](https://cloud.githubusercontent.com/assets/261635/16793677/9dea222a-4887-11e6-892a-45a6a6ce49a7.jpg)

### after 3 days

More than 1/2 the bricks have hauled themselves away

![img_1274](https://cloud.githubusercontent.com/assets/261635/16793689/af7e0088-4887-11e6-93ba-85c7a615a705.jpg)

**Comment by msimerson** [comment]
The pile continues to shrink as folks stop by and haul away the bricks and blocks, one carload at a time. Yay.

**Comment by msimerson** [comment]
I sorted and stacked the bricks by type:

![img_1309](https://cloud.githubusercontent.com/assets/261635/17113008/768b5912-525d-11e6-9673-8119356d1e83.jpg)
![img_1312](https://cloud.githubusercontent.com/assets/261635/17113009/7691d26a-525d-11e6-949d-65786215b02e.jpg)

**Comment by msimerson** [comment]
Update: haul away scheduled for Saturday Aug 20.

**Comment by msimerson** [comment]
We also removed most of the small brick wall in the front yard.
