### ISSUE TITLE
crawl space #1 seismic upgrades

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#82]
### todo
- [x] attach interior columns to the floor breams with 4x AC6 metal post caps (#80)
- [x] remove all gas appliances (#71) and plumbing.
- [ ] attach sill to rim joist with A35 framing angles (20 pcs. @ $0.90 = $20)
- anchor crawl space sill plate to foundation with:
  - [Simpson UFP10 Universal Foundation Plate](http://www.strongtie.com/foundationanchors_concreteconnectorsandanchors/ufp_plate/p/ufp) (20 pcs. @  $17 = $340)
    - [x] South wall (Aug 6th)
    - [x] West wall (Nov 12)
    - [x] North wall
  - Titen HD concrete anchors, 1/2" x 5" (26-40)
    - [ ] East wall
