### ISSUE TITLE
replace the mbr sliding door with window

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#85]
### background
- to make this easier, do this before tearing off the upper deck platform.
### todo
- [x] remove siding from around the door
- [x] remove sliding door
- [x] frame in the opening for the new window
  - [x] glue the plywood to the studs
  - [x] use seismic nailing pattern
- [x] temporarily mount the new window

related to #86

**Comment by msimerson** [comment]
wall stripped of siding 

![img_0014](https://cloud.githubusercontent.com/assets/261635/17579075/e73268d2-5f45-11e6-8256-6353fcb9cbc2.jpg)

door removed.

![img_1306](https://cloud.githubusercontent.com/assets/261635/17113287/dcd855a2-525e-11e6-97ee-d36ba5402990.jpg)

Wall framed in and new window temporarily set

![img_1322](https://cloud.githubusercontent.com/assets/261635/17113370/509330de-525f-11e6-95a9-58fd03668767.jpg)

![img_1315](https://cloud.githubusercontent.com/assets/261635/17113303/f427e9fc-525e-11e6-8338-67169df94d21.jpg)
