### ISSUE TITLE
spray and eradicate all japanese knotweed

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#87]
We have Japanese Knotweed in a corner of our yard and in our neighbors yard. Digging it up (mechanical control) doesn't work. Paving over it doesn't work. 

Only spraying it with Imazapyr in late September, after it has flowered, when it's sucking sugars down into the roots, is proven to work. 
### todo
- [x] buy some Imazapyr (July 27)
- [x] spray our knotweed plants (September 10)
- [x] spray all the knotweed plants in the neighbors yards (Sept 10)

**Comment by msimerson** [comment]
The knotweed has been sprayed. Now we wait a couple weeks and hopefully watch with delight as the plants all die off.
