### ISSUE TITLE
Incandescent lightbulbs

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#9]
Replace them all with LED
# TODO
- [x] upstairs bathroom (3x)
- [x] upstairs bathroom (1x recessed)
- [x] downstairs bathroom (2x)
- [x] downstairs bonus room (2x low)
- [x] downstairs 2nd bonus room (2x low)
- [x] downstairs bedroom (2x low)
- [x] downstairs hall (2x low)
- [x] downstairs basement (4x)
- [x] downstairs stairwell (2x low)
- [x] upstairs bedroom 1 (2x low)
- [x] upstairs bedroom 2 (2x low)
- [x] upstairs bedroom 3 (2x low)
- [x] garage indoor flood
- [x] garage service door
- [x] garage door opener
- [x] outside, front (2x)
- [x] outside, west (2x), flood (4x)
- [x] outside, west, flood (4x)
- [x] outside, east
- [x] outside, basement door
- [x] crawlspace (2x)

**Comment by msimerson** [comment]
- [x] range hood
