### ISSUE TITLE
install new siding on the house

### ISSUE THREAD

**Issue by msimerson** [msimerson/330-NE-193rd-St#91]
### prereq
- [x] choose new siding
    - Hardi 8" reveal: $4,400
    - Cedar 6" reveal: $8,772
    - Cedar 4" reveal: $9,804
- [x] buy new siding
### todo walls
- [x] house South
- [x] house East
- [x] house West
- [x] house North
- [x] garage North
- [x] garage East
- [x] garage West
- [x] garage South
### todo steps
- [x] install house wrap / water control layer ([tyvek](http://www.homedepot.com/p/TYVEK-HomeWrap-9-ft-x-150-ft-Roll-Housewrap-D13499991/100422450) or similar)
- [x] flash door and window openings
- [x] install new windows (#8)
- [x] extend plumbing and electrical outlets
  - 7 1/2" past plywood (6" polyiso + 3/4 rainscreen + 3/4 depth of siding)
